# Generated by Django 3.2 on 2021-05-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210527_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='post_id',
            new_name='posts',
        ),
    ]
